name: Node.js CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
jobs:
  build:
    runs-on:
      ubuntu-latest
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      USER_EMAL: ${{ secrets.USER_EMAIL }}
      USER_NAME: ${{ secrets.USER_NAME }}
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install
        run: npm ci --cache .npm --prefer-offline
      - uses: actions/checkout@v3
      - name: Validate
        run: npm run lint
      - name: Test
        run: npm test
  realease:
    runs-on:
      ubuntu-latest
    needs: build
    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name != 'push' &&
      !contains(github.event.head_commit.message, 'chore: release')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Git configuration
        run: |
          git config user.email "$USER_EMAIL"
          git config user.name "Oskour"
          git remote set-url origin "https://$GITHUB_ACTOR:$TOKEN@github.com/${{ github.repository }}.git"
          git checkout ${{ github.ref_name }}
          git pull origin ${{ github.ref_name }} --rebase
      - name: Install dependencies and run release-it
        run: |
          npx --yes release-it --ci