name: Node.js CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
jobs:
  build:
    runs-on:
      ubuntu-latest
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install
        run: npm ci --cache .npm --prefer-offline
      - name: Validate
        run: npm run lint
      - name: Test
        run: npm test
  release:
    needs: build
    runs-on: ubuntu-latest

    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name != 'push' &&
      !contains(github.event.head_commit.message, 'chore: release')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git configuration
        run: |
          git config user.email "${{ secrets.GITLAB_USER_EMAIL }}"
          git config user.name "${{ secrets.GITLAB_USER_NAME }}"
          git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git checkout ${{ github.ref_name }}
          git pull origin ${{ github.ref_name }} --rebase

      - name: Install dependencies and run release-it
        run: |
          npx --yes release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}